class CreateKwikeeProducts < ActiveRecord::Migration
  def change
    create_table :kwikee_products do |t|
      t.text :allergens
      t.integer :brand_id
      t.text :brand_name
      t.text :cal_from_sat_tran_fat
      t.text :calories_per_serving
      t.text :carbo_per_serving
      t.text :carbo_uom
      t.text :case_count
      t.text :case_depth
      t.text :case_gtin
      t.text :case_height
      t.text :case_width
      t.text :category
      t.text :cholesterol_per_serving
      t.text :cholesterol_uom
      t.text :column_heading
      t.text :column_headings
      t.text :component_element
      t.text :component_elements
      t.text :consumable
      t.text :container_type
      t.text :custom_product_name
      t.text :department
      t.text :depth
      t.text :description
      t.text :diabetes_fc_values
      t.text :disease_claim
      t.text :display_depth
      t.text :display_height
      t.text :display_width
      t.text :division_name
      t.text :division_name_2
      t.text :dvp_biotin
      t.text :dvp_calcium
      t.text :dvp_carbo
      t.text :dvp_chloride
      t.text :dvp_cholesterol
      t.text :dvp_chromium
      t.text :dvp_copper
      t.text :dvp_fiber
      t.text :dvp_folic_acid
      t.text :dvp_iodide
      t.text :dvp_iodine
      t.text :dvp_iron
      t.text :dvp_magnesium
      t.text :dvp_manganese
      t.text :dvp_molybdenum
      t.text :dvp_niacin
      t.text :dvp_panthothenate
      t.text :dvp_phosphorus
      t.text :dvp_potassium
      t.text :dvp_protein
      t.text :dvp_riboflavin
      t.text :dvp_sat_tran_fat
      t.text :dvp_saturated_fat
      t.text :dvp_selenium
      t.text :dvp_sodium
      t.text :dvp_sugar
      t.text :dvp_thiamin
      t.text :dvp_total_fat
      t.text :dvp_vitamin_a
      t.text :dvp_vitamin_b12
      t.text :dvp_vitamin_b6
      t.text :dvp_vitamin_c
      t.text :dvp_vitamin_d
      t.text :dvp_vitamin_e
      t.text :dvp_vitamin_k
      t.text :dvp_zinc
      t.text :extra_text_2
      t.text :extra_text_3
      t.text :extra_text_4
      t.text :fat_calories_per_serving
      t.text :fat_free
      t.text :fiber_per_serving
      t.text :fiber_uom
      t.text :flavor
      t.text :footer
      t.text :footers
      t.text :footnote
      t.text :footnotes
      t.text :format
      t.text :gluten_free
      t.datetime :gpc_attributes_assigned
      t.integer :gpc_brick_id
      t.text :gpc_brick_name
      t.integer :gpc_class_id
      t.text :gpc_class_name
      t.integer :gpc_family_id
      t.text :gpc_family_name
      t.integer :gpc_segment_id
      t.text :gpc_segment_name
      t.text :gtin
      t.text :guarantee_analysis
      t.text :guarantees
      t.text :header
      t.text :headers
      t.text :height
      t.text :image_indicator
      t.text :indications_copy
      t.text :ingredient_code
      t.text :ingredients
      t.text :insol_fiber_per_serving
      t.text :insol_fiber_per_serving_uom
      t.text :instruction_copy_1
      t.text :instruction_copy_2
      t.text :instruction_copy_3
      t.text :instruction_copy_4
      t.text :instruction_copy_5
      t.text :interactions_copy
      t.text :is_variant_flag
      t.text :kosher
      t.text :kwikee_why_buy
      t.datetime :last_publish_date
      t.text :legal
      t.text :low_fat
      t.integer :manufacturer_id
      t.text :manufacturer_name
      t.datetime :mfr_approved_date
      t.text :model
      t.text :mono_unsat_fat
      t.text :mono_unsat_fat_uom
      t.text :multiple_shelf_facings
      t.text :name
      t.text :nutrient_claim_1
      t.text :nutrient_claim_2
      t.text :nutrient_claim_3
      t.text :nutrient_claim_4
      t.text :nutrient_claim_5
      t.text :nutrient_claim_6
      t.text :nutrient_claim_7
      t.text :nutrient_claim_8
      t.text :nutrient_disclaimer_1
      t.text :nutrient_disclaimer_2
      t.text :nutrient_disclaimer_3
      t.text :nutrient_disclaimer_4
      t.text :nutrition_footnotes_1
      t.text :nutrition_footnotes_2
      t.text :nutrition_head_1
      t.text :nutrition_head_2
      t.text :nutrition_label
      t.text :omega_3_polyunsat
      t.text :omega_3_polyunsat_uom
      t.text :omega_6_polyunsat
      t.text :omega_6_polyunsat_uom
      t.text :omega_9_polyunsat
      t.text :omega_9_polyunsat_uom
      t.text :organic
      t.text :other_nutrient_statement
      t.text :override_manufacturer_tasks
      t.text :peg_down
      t.text :peg_right
      t.text :physical_weight_lb
      t.text :physical_weight_oz
      t.text :poly_unsat_fat
      t.text :poly_unsat_fat_uom
      t.text :post_consumer
      t.text :potassium_per_serving
      t.text :potassium_uom
      t.text :primary_gtin
      t.text :primary_type
      t.text :primary_version
      t.text :product_count
      t.text :product_form
      t.integer :product_id
      t.text :product_name
      t.text :product_size
      t.text :product_type
      t.text :profile_id
      t.text :promotion
      t.text :protein_per_serving
      t.text :protein_uom
      t.text :romance_copy_1
      t.text :romance_copy_2
      t.text :romance_copy_3
      t.text :romance_copy_4
      t.text :romance_copy_category
      t.text :sat_fat_per_serving
      t.text :sat_fat_uom
      t.text :section_id
      t.text :section_name
      t.text :segment
      t.text :segments
      t.text :sensible_solutions
      t.text :serving_size
      t.text :serving_size_uom
      t.text :servings_per_container
      t.text :size_description_1
      t.text :size_description_2
      t.text :sodium_per_serving
      t.text :sodium_uom
      t.text :sol_fiber_per_serving
      t.text :sol_fiber_per_serving_uom
      t.text :ss_claim_1
      t.text :ss_claim_2
      t.text :ss_claim_3
      t.text :ss_claim_4
      t.text :starch_per_serving
      t.text :starch_per_serving_uom
      t.text :sub_number
      t.text :sugar_per_serving
      t.text :sugar_uom
      t.text :suger_alc_per_serving
      t.text :suger_alc_per_serving_uom
      t.text :supplemental_facts
      t.text :total_fat_per_serving
      t.text :total_fat_uom
      t.text :trans_fat_per_serving
      t.text :trans_fat_uom
      t.text :tray_count
      t.text :tray_depth
      t.text :tray_height
      t.text :tray_width
      t.text :unit_container
      t.text :unit_size
      t.text :unit_uom
      t.text :uom
      t.text :upc_10
      t.text :upc_12
      t.text :value
      t.text :values
      t.text :variant_name_1
      t.text :variant_name_2
      t.text :variant_value_1
      t.text :variant_value_2
      t.text :vm_claim_1
      t.text :vm_claim_2
      t.text :vm_claim_3
      t.text :vm_claim_4
      t.text :vm_type_1
      t.text :vm_type_2
      t.text :vm_type_3
      t.text :vm_type_4
      t.text :warnings_copy
      t.text :why_buy_copy
      t.text :width

      t.timestamps
    end
  end
end
